server:
  port: 9191
spring:
  application:
    name: auth-server
  profiles:
    active: PROD
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    #username: root
    #password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: info
#spring:
#  security:
#    user:
#      name: duminda
#      password: duminda123
#      roles: ADMIN,USER
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
